FROM node:20-slim
WORKDIR /app

COPY KT_LOGIC_123-dctor-web-ac56e70abd75/backend/package*.json ./
COPY KT_LOGIC_123-dctor-web-ac56e70abd75/backend/packages ./packages
RUN npm ci

COPY KT_LOGIC_123-dctor-web-ac56e70abd75/backend/ ./
RUN npm run build:render

ENV NODE_CONFIG_DIR=./.tmp-config
ENV NODE_ENV=dev
ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD ["npm", "run", "start:render"]
