services:
  - type: web
    name: dctor-backend
    runtime: node
    rootDir: KT_LOGIC_123-dctor-web-ac56e70abd75/backend
    buildCommand: npm ci && npm run build:render
    startCommand: npm run start:render
    healthCheckPath: /api/users/count
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: dev
      - key: NODE_CONFIG_DIR
        value: ./.tmp-config

  - type: web
    name: dctor-frontend
    runtime: node
    rootDir: KT_LOGIC_123-dctor-frontend-f6bfd9d1d422
    buildCommand: npm ci && npm run build
    startCommand: npm run start -- --hostname 0.0.0.0 --port $PORT
    envVars:
      - key: API_HOSTPORT
        fromService:
          type: web
          name: dctor-backend
          property: hostport
      - key: __NEXT_PRIVATE_PREBUNDLED_REACT
        value: experimental
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
