FROM hasura/graphql-data-connector:v2.35.1 AS STANDARD

FROM public.ecr.aws/lambda/java:17 AS SERVERLESS
# FROM public.ecr.aws/lambda/go:latest AS SERVERLESS
# FROM public.ecr.aws/lambda/provided:latest AS SERVERLESS


COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.0 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=7000

WORKDIR /

COPY --from=STANDARD --chmod=755 /app /app

WORKDIR /tmp

ENTRYPOINT ["/app/run-java.sh"]
