version = 0.1
[default.deploy.parameters]
stack_name = "dctor-dev-graphql-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ky1s09siikqy"
s3_prefix = "dctor-dev-graphql-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["DCAgentFn=726677866191.dkr.ecr.us-east-1.amazonaws.com/dctordevgraphqlservicea74dcb2b/dcagentfndd2543c6repo", "LFnEngine=726677866191.dkr.ecr.us-east-1.amazonaws.com/dctordevgraphqlservicea74dcb2b/lfnengine7d9747a7repo"]
