# FROM postgres:15.1
FROM postgis/postgis:15-3.3

# RUN apt-get update && apt-get install -y \
#     postgresql-15-postgis-3         \
#     postgresql-15-postgis-3-scripts \
#     postgresql-client                  \
#     postgresql-contrib-15             \
#   && rm -rf /var/lib/apt/lists/*