[zocdocdb]
Description         = Example for OpenLDAP's back-sql
Driver              = MySQL
Trace               = No
Database            = zocdocdb
Servername          = rdb
UserName            = zocdoc-platform
Password            = 123456
Port                = 3306
;Protocol            = 6.4
ReadOnly            = No
RowVersioning       = No
ShowSystemTables    = No
ShowOidColumn       = No
FakeOidIndex        = No
ConnSettings        =
